In [29]:
import GPy
import numpy as np

## 1.GPy

In [31]:
X = np.random.rand(10)
X = np.atleast_2d(X)
Y = X**2 + np.random.randn(10)

In [51]:
X

array([[0.31188314, 0.6924897 , 0.72949339, 0.29556008, 0.93199169,
        0.06362345, 0.94260454, 0.35234279, 0.02330867, 0.84263156]])

In [41]:
kern = GPy.kern.Matern52(input_dim = 1, ARD=True)
kern

In [42]:
kern.lengthscale._optimizer_copy_transformed = True

In [43]:
kern.variance.values

array([1.])

In [44]:
noise_var = Y.var()*0.01

In [45]:
model = GPy.models.GPRegression(X, Y, kernel=kern, noise_var=noise_var)

In [47]:
model.Gaussian_noise.variance.values

array([0.00504926])

## 2. GPyOpt

In [48]:
from GPyOpt.models import GPModel

In [49]:
g = GPModel()

In [50]:
g._create_model(X, Y)

In [ ]:
g.posterior_sam